import "../styles/globals.css";
import Head from "next/head";
import Header from "../components/Header";

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>FoodPerDollar</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<div className="container">
				<Component {...pageProps} />
			</div>
		</>
	);
}

export default MyApp;
